function createfigure(X1, YMatrix1, XData1, YData1, XData2)
%CREATEFIGURE(X1, YMATRIX1, XDATA1, YDATA1, XDATA2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata

%  Auto-generated by MATLAB on 13-May-2019 18:27:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'ZMinorGrid','on','YMinorGrid','on',...
    'XMinorGrid','on',...
    'XTick',[0 300 600],...
    'FontSize',20);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-200 800]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',6,'Parent',axes1);
set(plot1(1),'DisplayName','Sit');
set(plot1(2),'DisplayName','Stand','MarkerSize',10);
set(plot1(3),'DisplayName','Walk');

% Create line
line(XData1,YData1,'Parent',axes1,'LineWidth',3,'LineStyle',':');

% Create line
line(XData2,XData1,'Parent',axes1,'LineWidth',3,'LineStyle',':');

% Create xlabel
xlabel('Time relative to stimuli (ms)','FontSize',32);

% Create ylabel
ylabel('Potential (uV)','FontSize',32);

% Create title
title('Averaged ERP at Pz','FontSize',32);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',32);

