function Plot_bargraph_clear(yvector1, E1)
%CREATEFIGURE(YVECTOR1, E1)
%  YVECTOR1:  bar yvector
%  E1:  errorbar e

%  Auto-generated by MATLAB on 10-Jan-2020 19:02:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'YLim',[0 16],'YTick',[0 8 16],...
    'XTickLabel',{'Sit','Stand','Walk'},...
    'XTick',[1 2 3],...
    'FontSize',22,...
    'FontName','Times New Roman');
box(axes1,'on');
hold(axes1,'on');

% Create bar
bar(yvector1,'LineWidth',2,'FaceColor','none','BarWidth',0.4);

% Create errorbar
errorbar(yvector1,E1,'Marker','.','LineStyle','none','LineWidth',2,...
    'Color',[0 0 0]);

% Create ylabel
ylabel('Mean P3 Amplitude (µV)','FontSize',22);

