function createfigure(X1, YMatrix1, XData1, YData1, XData2, YData2, XData3, YData3, YData4)
%CREATEFIGURE(X1, YMATRIX1, XDATA1, YDATA1, XDATA2, YDATA2, XDATA3, YDATA3, YDATA4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  patch ydata
%  XDATA3:  patch xdata
%  YDATA3:  patch ydata
%  YDATA4:  patch ydata

%  Auto-generated by MATLAB on 10-Jan-2020 18:34:19

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'ZMinorGrid','on','LineWidth',2,...
    'YTick',[-10 0 10],...
    'XTick',[0 300 600],...
    'FontSize',30,...
    'FontName','Times New Roman');
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','Sit','Color',[0 0 1]);
set(plot1(2),'DisplayName','Stand','Color',[0 1 0]);
set(plot1(3),'DisplayName','Walk','Color',[1 0 0]);

% Create line
line(XData1,YData1,'Parent',axes1,'LineWidth',2,'LineStyle','--');

% Create line
line(XData2,XData1,'Parent',axes1,'LineWidth',2,'LineStyle','--');

% Create patch
patch('Parent',axes1,'YData',YData2,'XData',XData3,'FaceAlpha',0.4,...
    'FaceColor',[0.5 0.5 1],...
    'EdgeColor','none');

% Create patch
patch('Parent',axes1,'YData',YData3,'XData',XData3,'FaceAlpha',0.4,...
    'FaceColor',[0.5 1 0.5],...
    'EdgeColor','none');

% Create patch
patch('Parent',axes1,'YData',YData4,'XData',XData3,'FaceAlpha',0.4,...
    'FaceColor',[1 0.5 0.5],...
    'EdgeColor','none');

% Create xlabel
xlabel('Time relative to stimuli (ms)','FontSize',30);

% Create ylabel
ylabel('Potential (µV)','FontSize',30,'FontName','Times New Roman');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Orientation','horizontal','Location','south','FontSize',30);

