%% modelingP3rms
rms = [rms_sitA_allsubs, rms_sitB_allsubs, rms_sitC_allsubs,...
    rms_standA_allsubs, rms_standB_allsubs, rms_standC_allsubs,...
    rms_walkA_allsubs, rms_walkB_allsubs, rms_walkC_allsubs]';

session = categorical([ones(1,numel(rms_sitA_allsubs)) 2*ones(1,numel(rms_sitB_allsubs)) 3*ones(1,numel(rms_sitC_allsubs))...
    ones(1,numel(rms_standA_allsubs)) 2*ones(1,numel(rms_standB_allsubs)) 3*ones(1,numel(rms_standC_allsubs)) ...
    ones(1,numel(rms_walkA_allsubs)) 2*ones(1,numel(rms_walkB_allsubs)) 3*ones(1,numel(rms_walkC_allsubs))]');

condition = categorical([ones(1,numel(rms_sitA_allsubs)+numel(rms_sitB_allsubs)+numel(rms_sitC_allsubs))...
    2*ones(1,numel(rms_standA_allsubs)+numel(rms_standB_allsubs)+numel(rms_standC_allsubs))...
    3*ones(1,numel(rms_walkA_allsubs)+numel(rms_walkB_allsubs)+numel(rms_walkC_allsubs))]');

p3_mean = [p3_rms_allsubs_sitA(:,3); p3_rms_allsubs_sitB(:,3); p3_rms_allsubs_sitC(:,3);...
    p3_rms_allsubs_standA(:,3); p3_rms_allsubs_standB(:,3); p3_rms_allsubs_standC(:,3);...
    p3_rms_allsubs_walkA(:,3); p3_rms_allsubs_walkB(:,3); p3_rms_allsubs_walkC(:,3)];

tbl = table(rms,session,condition,p3_mean);

fitlm(tbl,'p3_mean~condition*session')