function [Time, Ax, Ay, Az, Seq] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, AX, AY, AZ, SEQ] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [TIME, AX, AY, AZ, SEQ] = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Time, Ax, Ay, Az, Seq] = importfile("Z:\Lab Member Folders\Margaret Swerdloff\EEG_gait\EEG\DSI_data\All\S014_walk_stand_sit_C_duration_Accel.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Jun-2021 16:18:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Ax", "Ay", "Az", "Seq"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time = tbl.Time;
Ax = tbl.Ax;
Ay = tbl.Ay;
Az = tbl.Az;
Seq = tbl.Seq;
end