function [Time,LE,F4,C4,P4,P3,C3,F3,Trigger,Time_Offset,ADC_Status,ADC_Sequence,Event,Comments] = importRaw(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [TIME,LE,F4,C4,P4,P3,C3,F3,TRIGGER,TIME_OFFSET,ADC_STATUS,ADC_SEQUENCE,EVENT,COMMENTS]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME,LE,F4,C4,P4,P3,C3,F3,TRIGGER,TIME_OFFSET,ADC_STATUS,ADC_SEQUENCE,EVENT,COMMENTS]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Time,LE,F4,C4,P4,P3,C3,F3,Trigger,Time_Offset,ADC_Status,ADC_Sequence,Event,Comments] = importfile1('Maggie_Walk_TTHigh_ArduinoRecording_10min_1sISI_v2_raw_manualFix.csv',17, 202052);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/02/01 00:20:49

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 17;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
 dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
LE = dataArray{:, 2};
F4 = dataArray{:, 3};
C4 = dataArray{:, 4};
P4 = dataArray{:, 5};
P3 = dataArray{:, 6};
C3 = dataArray{:, 7};
F3 = dataArray{:, 8};
Trigger = dataArray{:, 9};
Time_Offset = dataArray{:, 10};
ADC_Status = dataArray{:, 11};
ADC_Sequence = dataArray{:, 12};
Event = dataArray{:, 13};
Comments = dataArray{:, 14};


