function fiveKnocksAccel = importAccel(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FIVEKNOCKSACCEL = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  FIVEKNOCKSACCEL = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  fiveKnocksAccel = importfile("Z:\Lab Member folders\Margaret Swerdloff\EEG_gait\EEG\DSI_data\StroopAudio\fiveKnocks_Accel.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Jan-2021 15:25:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Ax", "Ay", "Az", "Seq"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
fiveKnocksAccel = readtable(filename, opts);

end